# Generated by Django 5.1 on 2024-09-04 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewhistory',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='viewhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='SearchHistory',
        ),
        migrations.DeleteModel(
            name='ViewHistory',
        ),
    ]
