# Generated by Django 5.1 on 2024-09-10 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
    ]
